v = int(input('Tabuada do: '))

print('{} x 1 = {}'.format(v, v * 1))
print('{} x 2 = {}'.format(v, v * 2))
print('{} x 3 = {}'.format(v, v * 3))
print('{} x 4 = {}'.format(v, v * 4))
print('{} x 5 = {}'.format(v, v * 5))
print('{} x 6 = {}'.format(v, v * 6))
print('{} x 7 = {}'.format(v, v * 7))
print('{} x 8 = {}'.format(v, v * 8))
print('{} x 9 = {}'.format(v, v * 9))
print('{} x 10 = {}'.format(v, v * 10))